export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Business Listings',
    route: '/listings',
    description: 'Local studios, cafés, and services we have checked in person.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Classifieds',
    route: '/classifieds',
    description: 'Short posts for roles, rentals, and neighbourhood notices.',
    contentType: 'classified',
    enabled: false,
  },
  {
  key: 'article',
  label: 'Article',
  route: '/article',
  description: 'Curated article content.',
  contentType: 'article',
  enabled: true,
},
  {
    key: 'image',
    label: 'Images',
    route: '/images',
    description: 'Photo essays and visual stories that pair with our writing.',
    contentType: 'image',
    enabled: false,
  },
  {
    key: 'profile',
    label: 'Profiles',
    route: '/profile',
    description: 'Writers, photographers, and partner desks we work with.',
    contentType: 'profile',
    enabled: false,
  },
  {
    key: 'sbm',
    label: 'Reading list',
    route: '/sbm',
    description: 'Sources and rabbit holes behind each cover story.',
    contentType: 'social',
    enabled: true,
  },
  {
    key: 'comment',
    label: 'Blog Commenting',
    route: '/blog',
    description: 'Reader letters and threaded responses on the blog.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'PDF Library',
    route: '/pdf',
    description: 'Printable briefings, reading lists, and PDF companions.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Organizations',
    route: '/team',
    description: 'Studios, nonprofits, and collectives we profile.',
    contentType: 'profile',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listings',
  classified: '/classifieds',
  article: '/articles',
  image: '/images',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
