export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Business Listing',
    route: '/listing',
    description: 'Local studios, cafés, and services we have checked in person.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Classified',
    route: '/classified',
    description: 'Short posts for roles, rentals, and neighbourhood notices.',
    contentType: 'classified',
    enabled: false,
  },
  {
  key: 'article',
  label: 'Article',
  route: '/article',
  description: 'Curated article content.',
  contentType: 'article',
  enabled: true,
},
  {
    key: 'image',
    label: 'Image',
    route: '/image',
    description: 'Photo essays and visual stories that pair with our writing.',
    contentType: 'image',
    enabled: false,
  },
  {
    key: 'profile',
    label: 'Profile',
    route: '/profile',
    description: 'Writers, photographers, and partner desks we work with.',
    contentType: 'profile',
    enabled: false,
  },
  {
    key: 'sbm',
    label: 'Social Bookmarking',
    route: '/sbm',
    description: 'Sources and rabbit holes behind each cover story.',
    contentType: 'sbm',
    enabled: true,
  },
  {
    key: 'comment',
    label: 'Comment',
    route: '/blog',
    description: 'Reader letters and threaded responses on the blog.',
    contentType: 'comment',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'PDF',
    route: '/pdf',
    description: 'Printable briefings, reading lists, and PDF companions.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Organization',
    route: '/team',
    description: 'Studios, nonprofits, and collectives we profile.',
    contentType: 'org',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listing',
  classified: '/classified',
  article: '/article',
  image: '/image',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
